name: Build and deploy ASP.Net Core app to Azure Web App - invoice-api-romi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build invoice-server-starter/Invoices.Api/Invoices.Api.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish invoice-server-starter/Invoices.Api/Invoices.Api.csproj -c Release -o ./publish_output

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish_output

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish_output

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_16BB25DD88794A9F979EF8547D145527 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_70EB6D0F52924A0F917874026CC927DA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_391E61CE2BDC402B8FA49E00698C32F5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'invoice-api-romi'
          slot-name: 'Production'
          package: ./publish_output
